-- 20251011T204500Z__functions_and_triggers.sql
-- Phase M0 supplementary functions and triggers supporting automation

-- Function to activate farm members and stamp joined_at
CREATE OR REPLACE FUNCTION public.set_joined_at_timestamp()
RETURNS TRIGGER AS 
BEGIN
  IF NEW.status = 'active' AND (OLD.status IS DISTINCT FROM 'active') THEN
    NEW.joined_at = COALESCE(NEW.joined_at, TIMEZONE('utc', NOW()));
  END IF;
  RETURN NEW;
END;
 LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_joined_at ON public.farm_members;
CREATE TRIGGER trg_set_joined_at
  BEFORE UPDATE ON public.farm_members
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_joined_at_timestamp();

-- Convenience function for creating farms with membership
CREATE OR REPLACE FUNCTION public.create_farm_with_owner(
  _name TEXT,
  _country TEXT DEFAULT NULL,
  _timezone TEXT DEFAULT 'UTC'
) RETURNS UUID AS 
DECLARE
  _profile UUID;
  _farm UUID;
BEGIN
  SELECT id INTO _profile FROM public.profiles WHERE user_id = auth.uid();
  IF _profile IS NULL THEN
    RAISE EXCEPTION 'Profile not found for user %', auth.uid();
  END IF;

  INSERT INTO public.farms (owner_profile_id, name, country, timezone)
  VALUES (_profile, _name, _country, _timezone)
  RETURNING id INTO _farm;

  INSERT INTO public.farm_members (farm_id, profile_id, role_id, status, joined_at)
  SELECT
    _farm,
    _profile,
    r.id,
    'active',
    TIMEZONE('utc', NOW())
  FROM public.roles r
  WHERE r.code = 'owner';

  RETURN _farm;
END;
 LANGUAGE plpgsql SECURITY DEFINER;

-- Function to enqueue simple in-app notifications (table to be created later)
CREATE OR REPLACE FUNCTION public.enqueue_notification(
  _profile_id UUID,
  _type TEXT,
  _title TEXT,
  _body TEXT,
  _metadata JSONB DEFAULT '{}'::jsonb
) RETURNS VOID AS 
BEGIN
  INSERT INTO public.notifications_queue (profile_id, type, title, body, metadata, created_at)
  VALUES (_profile_id, _type, _title, _body, _metadata, TIMEZONE('utc', NOW()));
END;
 LANGUAGE plpgsql;

-- Create queue table if not exists (temporary until final notifications table is versioned)
CREATE TABLE IF NOT EXISTS public.notifications_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  processed_at TIMESTAMPTZ
);

ALTER TABLE public.notifications_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profile can read its notification queue"
  ON public.notifications_queue FOR SELECT
  USING (profile_id = public.current_profile_id());

CREATE POLICY "service role can insert notifications"
  ON public.notifications_queue FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

-- Function to mark notifications processed
CREATE OR REPLACE FUNCTION public.mark_notification_processed(_id BIGINT)
RETURNS VOID AS 
BEGIN
  UPDATE public.notifications_queue
  SET processed_at = TIMEZONE('utc', NOW())
  WHERE id = _id;
END;
 LANGUAGE plpgsql;
