-- Task template and notification infrastructure
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET default_tablespace = '';
SET default_table_access_method = heap;

------------------------------------------------------------------------
-- Task templates
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.task_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT,
  category TEXT NOT NULL CHECK (
    category IN ('reproduction', 'health', 'logistics', 'monitoring')
  ),
  scope_type TEXT NOT NULL CHECK (
    scope_type IN ('litter', 'treatment', 'custom')
  ),
  species_id BIGINT REFERENCES public.species_config(id) ON DELETE SET NULL,
  default_anchor TEXT NOT NULL DEFAULT 'template_start' CHECK (
    default_anchor IN ('template_start', 'mating_date', 'kindling_date', 'custom_date')
  ),
  visibility TEXT NOT NULL DEFAULT 'private' CHECK (
    visibility IN ('private', 'shared_team', 'library')
  ),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  tags TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at TIMESTAMPTZ,
  CONSTRAINT task_templates_slug_unique
    UNIQUE (profile_id, slug)
    DEFERRABLE INITIALLY IMMEDIATE
);

COMMENT ON TABLE public.task_templates IS
  'Reusable task templates aligned with Everbreed quick schedules.';

CREATE INDEX IF NOT EXISTS task_templates_profile_idx
  ON public.task_templates (profile_id, is_active, category);

------------------------------------------------------------------------
-- Task template steps
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.task_template_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id UUID NOT NULL REFERENCES public.task_templates(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  title TEXT NOT NULL,
  task_type TEXT NOT NULL,
  category TEXT NOT NULL CHECK (
    category IN ('reproduction', 'health', 'logistics', 'monitoring')
  ),
  description TEXT,
  offset_days INTEGER NOT NULL DEFAULT 0 CHECK (offset_days BETWEEN -120 AND 365),
  offset_minutes INTEGER NOT NULL DEFAULT 0 CHECK (offset_minutes BETWEEN -4320 AND 4320),
  anchor TEXT NOT NULL DEFAULT 'template_start' CHECK (
    anchor IN (
      'template_start',
      'previous_step',
      'mating_date',
      'palpation_date',
      'kindling_date',
      'weaning_date',
      'custom_date'
    )
  ),
  auto_complete_rule JSONB NOT NULL DEFAULT '{}'::JSONB,
  notification_offsets INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (
    priority IN ('normal', 'important', 'critical')
  ),
  assign_to TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT task_template_steps_unique_position
    UNIQUE (template_id, position)
);

COMMENT ON TABLE public.task_template_steps IS
  'Ordered steps generated from a task template.';

CREATE INDEX IF NOT EXISTS task_template_steps_template_idx
  ON public.task_template_steps (template_id, position);

------------------------------------------------------------------------
-- Task template assignments
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.task_template_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  template_id UUID NOT NULL REFERENCES public.task_templates(id) ON DELETE CASCADE,
  scope_type TEXT NOT NULL CHECK (
    scope_type IN ('litter', 'treatment', 'custom')
  ),
  scope_id UUID,
  anchor_type TEXT NOT NULL DEFAULT 'template_start' CHECK (
    anchor_type IN (
      'template_start',
      'custom_date',
      'mating_date',
      'palpation_date',
      'kindling_date',
      'weaning_date'
    )
  ),
  anchor_date DATE NOT NULL,
  anchor_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  status TEXT NOT NULL DEFAULT 'active' CHECK (
    status IN ('active', 'completed', 'cancelled')
  ),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.task_template_assignments IS
  'Links a template to a litter, treatment or custom scope and tracks generated tasks.';

CREATE INDEX IF NOT EXISTS task_template_assignments_profile_idx
  ON public.task_template_assignments (profile_id, status);

CREATE INDEX IF NOT EXISTS task_template_assignments_scope_idx
  ON public.task_template_assignments (scope_type, scope_id);

------------------------------------------------------------------------
-- Task template assignment events
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.task_template_assignment_events (
  assignment_id UUID NOT NULL REFERENCES public.task_template_assignments(id) ON DELETE CASCADE,
  step_id BIGINT NOT NULL REFERENCES public.task_template_steps(id) ON DELETE CASCADE,
  event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (
    status IN ('active', 'detached')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (assignment_id, step_id, event_id)
);

COMMENT ON TABLE public.task_template_assignment_events IS
  'Join table linking generated events to template steps for later resync.';

CREATE INDEX IF NOT EXISTS task_template_assignment_events_event_idx
  ON public.task_template_assignment_events (event_id);

------------------------------------------------------------------------
-- Notification preferences
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  channel TEXT NOT NULL CHECK (
    channel IN ('local', 'email', 'sms')
  ),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  quiet_hours JSONB NOT NULL DEFAULT '{}'::JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT notification_preferences_unique_channel
    UNIQUE (profile_id, user_id, channel)
);

COMMENT ON TABLE public.notification_preferences IS
  'Per user notification settings controlling enabled channels and quiet hours.';

CREATE INDEX IF NOT EXISTS notification_preferences_profile_idx
  ON public.notification_preferences (profile_id, user_id);

------------------------------------------------------------------------
-- Notifications outbox
------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.notifications_outbox (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (
    channel IN ('email', 'sms')
  ),
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'processing', 'sent', 'failed')
  ),
  error_message TEXT,
  scheduled_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  task_id UUID,
  template_assignment_id UUID REFERENCES public.task_template_assignments(id) ON DELETE SET NULL,
  template_step_id BIGINT REFERENCES public.task_template_steps(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.notifications_outbox IS
  'Queue of external notifications (email/SMS) awaiting delivery by a background worker.';

CREATE INDEX IF NOT EXISTS notifications_outbox_profile_idx
  ON public.notifications_outbox (profile_id, status, channel);

------------------------------------------------------------------------
-- Events table linkage
------------------------------------------------------------------------

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS task_template_assignment_id UUID REFERENCES public.task_template_assignments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS task_template_step_id BIGINT REFERENCES public.task_template_steps(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS events_template_link_idx
  ON public.events (task_template_assignment_id, task_template_step_id);

COMMENT ON COLUMN public.events.task_template_assignment_id IS
  'Reference to task_template_assignments when an event originates from a template.';

COMMENT ON COLUMN public.events.task_template_step_id IS
  'Reference to task_template_steps when an event originates from a template step.';

------------------------------------------------------------------------
-- Row level security & triggers
------------------------------------------------------------------------

ALTER TABLE public.task_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_assignment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications_outbox ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.task_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_steps FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_assignments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_assignment_events FORCE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences FORCE ROW LEVEL SECURITY;
ALTER TABLE public.notifications_outbox FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS task_templates_owner_all ON public.task_templates;
CREATE POLICY task_templates_owner_all
  ON public.task_templates
  FOR ALL
  USING (profile_id = auth.uid() OR auth.role() = 'service_role')
  WITH CHECK (profile_id = auth.uid() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS task_template_steps_owner_all ON public.task_template_steps;
CREATE POLICY task_template_steps_owner_all
  ON public.task_template_steps
  FOR ALL
  USING (profile_id = auth.uid() OR auth.role() = 'service_role')
  WITH CHECK (profile_id = auth.uid() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS task_template_assignments_owner_all ON public.task_template_assignments;
CREATE POLICY task_template_assignments_owner_all
  ON public.task_template_assignments
  FOR ALL
  USING (profile_id = auth.uid() OR auth.role() = 'service_role')
  WITH CHECK (profile_id = auth.uid() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS task_template_assignment_events_owner_all ON public.task_template_assignment_events;
CREATE POLICY task_template_assignment_events_owner_all
  ON public.task_template_assignment_events
  FOR ALL
  USING (profile_id = auth.uid() OR auth.role() = 'service_role')
  WITH CHECK (profile_id = auth.uid() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS notification_preferences_owner_all ON public.notification_preferences;
CREATE POLICY notification_preferences_owner_all
  ON public.notification_preferences
  FOR ALL
  USING (
    profile_id = auth.uid()
    OR user_id = auth.uid()
    OR auth.role() = 'service_role'
  )
  WITH CHECK (
    profile_id = auth.uid()
    OR user_id = auth.uid()
    OR auth.role() = 'service_role'
  );

DROP POLICY IF EXISTS notifications_outbox_owner_manage ON public.notifications_outbox;
CREATE POLICY notifications_outbox_owner_manage
  ON public.notifications_outbox
  FOR ALL
  USING (
    profile_id = auth.uid()
    OR auth.role() = 'service_role'
  )
  WITH CHECK (
    profile_id = auth.uid()
    OR auth.role() = 'service_role'
  );

DROP TRIGGER IF EXISTS trg_task_templates_timestamps ON public.task_templates;
CREATE TRIGGER trg_task_templates_timestamps
  BEFORE UPDATE ON public.task_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();

DROP TRIGGER IF EXISTS trg_task_template_steps_timestamps ON public.task_template_steps;
CREATE TRIGGER trg_task_template_steps_timestamps
  BEFORE UPDATE ON public.task_template_steps
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();

DROP TRIGGER IF EXISTS trg_task_template_assignments_timestamps ON public.task_template_assignments;
CREATE TRIGGER trg_task_template_assignments_timestamps
  BEFORE UPDATE ON public.task_template_assignments
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();

DROP TRIGGER IF EXISTS trg_task_template_assignment_events_timestamps ON public.task_template_assignment_events;
CREATE TRIGGER trg_task_template_assignment_events_timestamps
  BEFORE UPDATE ON public.task_template_assignment_events
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();

DROP TRIGGER IF EXISTS trg_notification_preferences_timestamps ON public.notification_preferences;
CREATE TRIGGER trg_notification_preferences_timestamps
  BEFORE UPDATE ON public.notification_preferences
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();

DROP TRIGGER IF EXISTS trg_notifications_outbox_timestamps ON public.notifications_outbox;
CREATE TRIGGER trg_notifications_outbox_timestamps
  BEFORE UPDATE ON public.notifications_outbox
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_maintain_timestamps();
