-- Realign core livestock tables with initial Khodan schema + seed demo data
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET default_tablespace = '';
SET default_table_access_method = heap;

BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA extensions;

-- -------------------------------------------------------------------
-- Profiles
-- -------------------------------------------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS farm_name TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS locale TEXT,
  ADD COLUMN IF NOT EXISTS time_zone TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_email_unique
  ON public.profiles (email);

-- -------------------------------------------------------------------
-- Species configuration
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.species_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_name TEXT NOT NULL,
  gestation_days INTEGER,
  weaning_days INTEGER,
  events_schema JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

ALTER TABLE public.species_config
  ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS gestation_days INTEGER,
  ADD COLUMN IF NOT EXISTS weaning_days INTEGER,
  ADD COLUMN IF NOT EXISTS events_schema JSONB NOT NULL DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS species_config_profile_name_unique
  ON public.species_config (profile_id, species_name);

CREATE INDEX IF NOT EXISTS species_config_profile_idx
  ON public.species_config (profile_id);

-- -------------------------------------------------------------------
-- Animals
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.animals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_id BIGINT NOT NULL REFERENCES public.species_config(id) ON DELETE CASCADE,
  tag_id TEXT NOT NULL,
  name TEXT,
  birth_date DATE NOT NULL,
  sex TEXT NOT NULL,
  status TEXT NOT NULL,
  image_url TEXT,
  sire_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  dam_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  cage_number TEXT,
  origin TEXT,
  entry_date DATE,
  first_breeding_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

ALTER TABLE public.animals
  ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS species_id BIGINT REFERENCES public.species_config(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS tag_id TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS sex TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS sire_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS dam_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS cage_number TEXT,
  ADD COLUMN IF NOT EXISTS origin TEXT,
  ADD COLUMN IF NOT EXISTS entry_date DATE,
  ADD COLUMN IF NOT EXISTS first_breeding_date DATE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS animals_profile_tag_unique
  ON public.animals (profile_id, tag_id);

CREATE INDEX IF NOT EXISTS animals_profile_species_idx
  ON public.animals (profile_id, species_id);

CREATE INDEX IF NOT EXISTS animals_genealogy_idx
  ON public.animals (sire_id, dam_id);

-- -------------------------------------------------------------------
-- Breeding records
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.breeding_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  doe_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
  buck_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
  mating_date DATE NOT NULL,
  palpation_date DATE,
  palpation_positive BOOLEAN,
  kindling_date DATE,
  kits_born_alive INTEGER CHECK (kits_born_alive IS NULL OR kits_born_alive >= 0),
  kits_born_dead INTEGER CHECK (kits_born_dead IS NULL OR kits_born_dead >= 0),
  adopted_kits_in INTEGER CHECK (adopted_kits_in IS NULL OR adopted_kits_in >= 0),
  kits_removed INTEGER CHECK (kits_removed IS NULL OR kits_removed >= 0),
  weaning_date DATE,
  kits_weaned INTEGER CHECK (kits_weaned IS NULL OR kits_weaned >= 0),
  average_weaning_weight NUMERIC(6, 3),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS breeding_records_profile_mating_idx
  ON public.breeding_records (profile_id, mating_date DESC);

CREATE INDEX IF NOT EXISTS breeding_records_animals_idx
  ON public.breeding_records (doe_id, buck_id);

-- -------------------------------------------------------------------
-- Breeding metrics
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.breeding_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_id BIGINT NOT NULL REFERENCES public.species_config(id) ON DELETE CASCADE,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_litters INTEGER NOT NULL DEFAULT 0 CHECK (total_litters >= 0),
  average_kits_born_alive NUMERIC(6, 3),
  average_kits_weaned NUMERIC(6, 3),
  total_kits_weaned INTEGER NOT NULL DEFAULT 0 CHECK (total_kits_weaned >= 0),
  top_doe_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  top_buck_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT breeding_metrics_period_check CHECK (period_end >= period_start)
);

CREATE UNIQUE INDEX IF NOT EXISTS breeding_metrics_unique_period
  ON public.breeding_metrics (profile_id, species_id, period_start, period_end);

-- -------------------------------------------------------------------
-- Events & animal_events
-- -------------------------------------------------------------------
ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS event_type TEXT,
  ADD COLUMN IF NOT EXISTS event_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS details JSONB NOT NULL DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS events_profile_date_idx
  ON public.events (profile_id, event_date DESC);

CREATE INDEX IF NOT EXISTS events_type_idx
  ON public.events (event_type);

ALTER TABLE public.animal_events
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS animal_events_animal_idx
  ON public.animal_events (animal_id);

-- -------------------------------------------------------------------
-- Sync queue
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sync_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  entity TEXT NOT NULL,
  operation TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error_message TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  scheduled_at TIMESTAMPTZ,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS sync_queue_profile_status_idx
  ON public.sync_queue (profile_id, status);

CREATE INDEX IF NOT EXISTS sync_queue_schedule_idx
  ON public.sync_queue (scheduled_at);

-- -------------------------------------------------------------------
-- Demo seed (safe to re-run)
-- -------------------------------------------------------------------
INSERT INTO public.profiles (id, email, farm_name, created_at, updated_at)
VALUES (
  'c96b2fdb-7a54-492c-a5fa-44bab270b27b',
  'demo@khodan.app',
  'Elevage Demo',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.species_config (
  profile_id,
  species_name,
  gestation_days,
  weaning_days,
  events_schema
)
VALUES (
  'c96b2fdb-7a54-492c-a5fa-44bab270b27b',
  'Lapin',
  31,
  35,
  '["mating","palpation","kindling","weaning"]'::JSONB
)
ON CONFLICT (profile_id, species_name) DO NOTHING;

WITH first_species AS (
  SELECT id, profile_id
  FROM public.species_config
WHERE profile_id = 'c96b2fdb-7a54-492c-a5fa-44bab270b27b'
  ORDER BY created_at
  LIMIT 1
)
INSERT INTO public.animals (
  id,
  profile_id,
  species_id,
  tag_id,
  name,
  birth_date,
  sex,
  status,
  cage_number,
  origin,
  entry_date
) SELECT
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001',
  fs.profile_id,
  fs.id,
  'demo-f-001',
  'Demo Doe',
  CURRENT_DATE - INTERVAL '420 days',
  'Femelle',
  'Actif',
  'C-101',
  'Elevage interne',
  CURRENT_DATE - INTERVAL '400 days'
FROM first_species fs
ON CONFLICT (id) DO NOTHING;

WITH first_species AS (
  SELECT id, profile_id
  FROM public.species_config
WHERE profile_id = 'c96b2fdb-7a54-492c-a5fa-44bab270b27b'
  ORDER BY created_at
  LIMIT 1
)
INSERT INTO public.animals (
  id,
  profile_id,
  species_id,
  tag_id,
  name,
  birth_date,
  sex,
  status,
  cage_number,
  origin,
  entry_date
) SELECT
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001',
  fs.profile_id,
  fs.id,
  'demo-m-001',
  'Demo Buck',
  CURRENT_DATE - INTERVAL '450 days',
  'Male',
  'Actif',
  'C-205',
  'Elevage interne',
  CURRENT_DATE - INTERVAL '430 days'
FROM first_species fs
ON CONFLICT (id) DO NOTHING;

WITH parents AS (
  SELECT
    'cccccccc-cccc-cccc-cccc-cccccccc0001'::UUID AS id,
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001'::UUID AS sire_id,
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001'::UUID AS dam_id
)
INSERT INTO public.animals (
  id,
  profile_id,
  species_id,
  tag_id,
  name,
  birth_date,
  sex,
  status,
  sire_id,
  dam_id,
  cage_number,
  origin,
  entry_date
)
SELECT
  parents.id,
  sc.profile_id,
  sc.id,
  'demo-kit-001',
  'Jeune Demo',
  CURRENT_DATE - INTERVAL '120 days',
  'Femelle',
  'Actif',
  parents.sire_id,
  parents.dam_id,
  'C-301',
  'Elevage interne',
  CURRENT_DATE - INTERVAL '110 days'
FROM public.species_config sc
CROSS JOIN parents
WHERE sc.profile_id = 'c96b2fdb-7a54-492c-a5fa-44bab270b27b'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.breeding_records (
  id,
  profile_id,
  doe_id,
  buck_id,
  mating_date,
  palpation_date,
  palpation_positive,
  kindling_date,
  kits_born_alive,
  kits_born_dead,
  weaning_date,
  kits_weaned
)
VALUES (
  'dddddddd-dddd-dddd-dddd-dddddddd0001',
  'c96b2fdb-7a54-492c-a5fa-44bab270b27b',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001',
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbb0001',
  CURRENT_DATE - INTERVAL '150 days',
  CURRENT_DATE - INTERVAL '135 days',
  TRUE,
  CURRENT_DATE - INTERVAL '120 days',
  8,
  0,
  CURRENT_DATE - INTERVAL '90 days',
  7
)
ON CONFLICT (id) DO NOTHING;

COMMIT;
