-- Initial relational schema for Khodan livestock management
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA extensions;

-- -------------------------------------------------------------------
--  Base tables
-- -------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  farm_name TEXT,
  phone TEXT,
  locale TEXT,
  time_zone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT profiles_email_unique UNIQUE (email)
);

COMMENT ON TABLE public.profiles IS 'User profile synced with auth.users, holds farm level settings.';
COMMENT ON COLUMN public.profiles.farm_name IS 'Display name for the farm shown across the app.';
COMMENT ON COLUMN public.profiles.deleted_at IS 'Soft delete marker used by offline sync.';

CREATE TABLE IF NOT EXISTS public.species_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_name TEXT NOT NULL,
  gestation_days INTEGER,
  weaning_days INTEGER,
  events_schema JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.species_config IS 'Per profile configuration for each species managed in the farm.';
COMMENT ON COLUMN public.species_config.events_schema IS 'Ordered list of event identifiers that drive breeding workflows.';

CREATE UNIQUE INDEX IF NOT EXISTS species_config_profile_name_unique
  ON public.species_config (profile_id, species_name);

CREATE INDEX IF NOT EXISTS species_config_profile_idx
  ON public.species_config (profile_id);

CREATE TABLE IF NOT EXISTS public.animals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_id BIGINT NOT NULL REFERENCES public.species_config(id) ON DELETE CASCADE,
  tag_id TEXT NOT NULL,
  name TEXT,
  birth_date DATE NOT NULL,
  sex TEXT NOT NULL,
  status TEXT NOT NULL,
  image_url TEXT,
  sire_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  dam_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  cage_number TEXT,
  origin TEXT,
  entry_date DATE,
  first_breeding_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.animals IS 'Livestock master data, including genealogy and housing metadata.';
COMMENT ON COLUMN public.animals.status IS 'Lifecycle indicator (alive, sold, deceased, etc.).';

CREATE UNIQUE INDEX IF NOT EXISTS animals_profile_tag_unique
  ON public.animals (profile_id, tag_id);

CREATE INDEX IF NOT EXISTS animals_profile_species_idx
  ON public.animals (profile_id, species_id);

CREATE INDEX IF NOT EXISTS animals_genealogy_idx
  ON public.animals (sire_id, dam_id);

CREATE TABLE IF NOT EXISTS public.breeding_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  doe_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
  buck_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
  mating_date DATE NOT NULL,
  palpation_date DATE,
  palpation_positive BOOLEAN,
  kindling_date DATE,
  kits_born_alive INTEGER CHECK (kits_born_alive IS NULL OR kits_born_alive >= 0),
  kits_born_dead INTEGER CHECK (kits_born_dead IS NULL OR kits_born_dead >= 0),
  adopted_kits_in INTEGER CHECK (adopted_kits_in IS NULL OR adopted_kits_in >= 0),
  kits_removed INTEGER CHECK (kits_removed IS NULL OR kits_removed >= 0),
  weaning_date DATE,
  kits_weaned INTEGER CHECK (kits_weaned IS NULL OR kits_weaned >= 0),
  average_weaning_weight NUMERIC(6, 3),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.breeding_records IS 'Detailed records for each mating cycle and its outcomes.';

CREATE INDEX IF NOT EXISTS breeding_records_profile_mating_idx
  ON public.breeding_records (profile_id, mating_date DESC);

CREATE INDEX IF NOT EXISTS breeding_records_animals_idx
  ON public.breeding_records (doe_id, buck_id);

CREATE TABLE IF NOT EXISTS public.breeding_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  species_id BIGINT NOT NULL REFERENCES public.species_config(id) ON DELETE CASCADE,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_litters INTEGER NOT NULL DEFAULT 0 CHECK (total_litters >= 0),
  average_kits_born_alive NUMERIC(6, 3),
  average_kits_weaned NUMERIC(6, 3),
  total_kits_weaned INTEGER NOT NULL DEFAULT 0 CHECK (total_kits_weaned >= 0),
  top_doe_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  top_buck_id UUID REFERENCES public.animals(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT breeding_metrics_period_check CHECK (period_end >= period_start)
);

COMMENT ON TABLE public.breeding_metrics IS 'Aggregated performance metrics powering dashboard KPIs.';

CREATE UNIQUE INDEX IF NOT EXISTS breeding_metrics_unique_period
  ON public.breeding_metrics (profile_id, species_id, period_start, period_end);

CREATE TABLE IF NOT EXISTS public.events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  event_date TIMESTAMPTZ NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.events IS 'Timeline of farm events, health checks, tasks and inventory actions.';

CREATE INDEX IF NOT EXISTS events_profile_date_idx
  ON public.events (profile_id, event_date DESC);

CREATE INDEX IF NOT EXISTS events_type_idx
  ON public.events (event_type);

CREATE TABLE IF NOT EXISTS public.animal_events (
  event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  animal_id UUID NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  PRIMARY KEY (event_id, animal_id, role)
);

COMMENT ON TABLE public.animal_events IS 'Association table between events and animals with contextual roles.';

CREATE INDEX IF NOT EXISTS animal_events_animal_idx
  ON public.animal_events (animal_id);

CREATE TABLE IF NOT EXISTS public.sync_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  entity TEXT NOT NULL,
  operation TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error_message TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  scheduled_at TIMESTAMPTZ,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.sync_queue IS 'Queue of offline first mutations to replay once the device is online.';

CREATE INDEX IF NOT EXISTS sync_queue_profile_status_idx
  ON public.sync_queue (profile_id, status);

CREATE INDEX IF NOT EXISTS sync_queue_schedule_idx
  ON public.sync_queue (scheduled_at);

-- -------------------------------------------------------------------
--  Seed data (optional, only if a profile exists)
-- -------------------------------------------------------------------

INSERT INTO public.profiles (id, email, farm_name)
SELECT
  u.id,
  COALESCE(u.email, CONCAT('user+', u.id::TEXT, '@example.com')),
  COALESCE(u.raw_user_meta_data ->> 'farm_name', 'Demo Farm')
FROM auth.users u
WHERE NOT EXISTS (
  SELECT 1
  FROM public.profiles p
  WHERE p.id = u.id
)
LIMIT 1;

WITH first_profile AS (
  SELECT id, email
  FROM public.profiles
  ORDER BY created_at
  LIMIT 1
)
INSERT INTO public.species_config (profile_id, species_name, gestation_days, weaning_days, events_schema)
SELECT fp.id, 'Lapin', 31, 35, '["mating","palpation","kindling","weaning"]'::JSONB
FROM first_profile fp
ON CONFLICT (profile_id, species_name) DO NOTHING;

WITH first_species AS (
  SELECT sc.id, sc.profile_id
  FROM public.species_config sc
  ORDER BY sc.created_at
  LIMIT 1
)
INSERT INTO public.animals (
  profile_id,
  species_id,
  tag_id,
  name,
  birth_date,
  sex,
  status,
  cage_number,
  origin,
  entry_date
)
SELECT
  fs.profile_id,
  fs.id,
  'demo-001',
  'Demo Doe',
  CURRENT_DATE - INTERVAL '420 days',
  'F',
  'active',
  'C-101',
  'demo',
  CURRENT_DATE - INTERVAL '400 days'
FROM first_species fs
WHERE NOT EXISTS (
  SELECT 1
  FROM public.animals a
  WHERE a.profile_id = fs.profile_id
    AND a.tag_id = 'demo-001'
);
