-- Migration pour ajouter la galerie d'images et les préférences utilisateur

-- 1. Table pour les images des animaux
-- Permet de lier plusieurs images à un seul animal.
create table public.animal_images (
    id bigint generated by default as identity primary key,
    animal_id uuid not null references public.animals (id) on delete cascade,
    image_url text not null,
    created_at timestamp with time zone not null default now()
);

-- Active la sécurité au niveau des lignes (RLS) pour cette table
alter table public.animal_images enable row level security;

-- Politique de sécurité : Les utilisateurs ne peuvent voir que les images
-- des animaux qui appartiennent à leur profil.
create policy "Users can view their own animal images"
    on public.animal_images for select
    using (auth.uid() = (select profile_id from public.animals where id = animal_id));

-- Politique de sécurité : Les utilisateurs peuvent insérer des images
-- uniquement pour les animaux qui leur appartiennent.
create policy "Users can insert images for their own animals"
    on public.animal_images for insert
    with check (auth.uid() = (select profile_id from public.animals where id = animal_id));


-- 2. Table pour les préférences utilisateur
-- Pour sauvegarder des réglages spécifiques à chaque utilisateur, comme les KPIs du dashboard.
create table public.user_preferences (
    profile_id uuid not null primary key references public.profiles (id) on delete cascade,
    dashboard_kpis text[],
    updated_at timestamp with time zone not null default now()
);

-- Active la sécurité au niveau des lignes (RLS)
alter table public.user_preferences enable row level security;

-- Politique de sécurité : Les utilisateurs ne peuvent accéder qu'à leurs propres préférences.
create policy "Users can manage their own preferences"
    on public.user_preferences for all
    using (auth.uid() = profile_id);